# Generated by Django 4.2.3 on 2023-07-15 18:03

from django.db import migrations, models
import ecommerce.ecom.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[ecommerce.ecom.validators.validate_nonnegative]),
        ),
    ]
